### PR TITLE
Updated primitive data types: added `u128`

### LINKED ISSUE #18: Primitive data types: u128
Added on rust 1.2.6, [`u128`](https://doc.rust-lang.org/std/primitive.u128.html)  is a new primitve data type which is currently not present in the site.

### PR DESCRIPTION
**Pull request by elementh**
Closes #18

### CODE REVIEW

**Comment by dumindu** [comment]
@elementh Thanks for informing about this missing type. I think PR will be more complete if you can add i128 as well. 

Files we need to update,
- https://github.com/learning-rust/site/blob/master/source/docs/a8.primitive_data_types.md : title & tables which shows min/ max values.
- https://github.com/learning-rust/site/blob/master/source/docs/d7.std_primitives_and_preludes.md : need to remove comments ` // i128 : nightly-only experimental API` and ` // u128 : nightly-only experimental API`; two places each.

**Comment by elementh** [comment]
@dumindu done! I also had to update the max-width since the site was broken with the width of the new row at the table.

Hope it's alright! Tell me if I need to correct something :)

**Comment by dumindu** [comment]
@elementh Instead changing `max-width`, I think it's better to add `overflow-x: scroll` to `.article-content`
themes/navy/source/css/_partial/page.styl  : line 123 :)

Also please update source/docs/a8.primitive_data_types.md : line 41 and 27

**Comment by elementh** [comment]
@dumindu Are you sure about the `overflox-x: scroll`? I did try that before `max-width` but it feels so wrong, and 100px don't really break anything; on the other side, that scroll-x feels like a rushed fix, at least in my screen.

**Comment by dumindu** [comment]
@elementh sorry for the very late response buddy. Let me check!

**Comment by elementh** [comment]
@dumindu no problem! Glad to help :)

**Comment by dumindu** [comment]
@elementh I didn't think that you reply to this quickly, and also I didn't want to make you wait to add another file change after all most 10 days because of my fault. Sorry for updating styles by myself. 

Actually we need `overflow-x: scroll` to fix styles on tablets. Also I prefer to keep `max-width:1200px` because it affects to [width of the paragraphs](https://en.wikipedia.org/wiki/Line_length) :)

**Comment by dumindu** [comment]
Site Updated! Sorry again for the late.

**Pull request merged**
