### PR TITLE
I18n/cn

### PR DESCRIPTION
**Pull request by ldwformat**

### CODE REVIEW

**Comment by dumindu** [comment]
Sorry, one more update https://github.com/learning-rust/site/commit/4ddd41560ab99602741b6ed1cefed3c867987051 . @ldwformat Also as I saw your branch is not having the error handing section added in few weeks ago.

**Comment by dumindu** [comment]
@ldwformat 
Hey buddy,
I know, this is not an easy task for a single person. And it's so time consuming. Let me know if any help is needed from my side, if you are still working on this.
Have a nice weekend!

**Comment by ldwformat** [comment]
@dumindu 
Hey, 
Sorry for the long disappearance.
Thanks for your kindness, I'm still working on this nice project, though, with a low-speed progress:sweat:. I've got some personal business done these months, which cost some time. Recently, I will focus on the translation of this project for weeks trying to keep the content to be updated with the main branch. A first completed Chinese version will be pushed after a few weeks. I hope :stuck_out_tongue_winking_eye:.
Btw, the Rust 2018 has been published, should we add some contents about that onto our pages?
Have a nice weekend~

**Comment by dumindu** [comment]
@ldwformat Unfortunately I also having a tough time due to instability of my career life and the issues of my current working place. Because of that I have to spend more time to practice more golang, devops stuff & etc. Even I love to spend more time on Rust and this project due to I'm all most dead after working time, I couldn't update more things in here. So, so far I can not give an exact timeline for Rust 2018.

Also we still having discussion like this https://www.reddit.com/r/rust/comments/b65ecn/modrs_in_rust_2018_yes_or_no/ ;)
Screen Shot 2019-03-28 at 11 24 33 AM

**Comment by juzhiyuan** [comment]
Any update? Maybe I could help translate this doc site with @ldwformat, a discussion is needed before working together.

**Comment by ldwformat** [comment]
Sorry for the long-time suspension about the
translation. There will be a draft version in a few days, would you like to
add some rust
2018 features onto it? How to add those contents appropriately is a rough
task😅



琚致远 <notifications@github.com> 于 2019年10月29日周二 14:04写道：

**Comment by juzhiyuan** [comment]
hi @ldwformat, I want to know the current process of translation work, and which part I could help you?

**Comment by ldwformat** [comment]
@juzhiyuan You can check out the latest update on my fork of this branch. The first two chapters have already been done, but I'm stuck on the c3. Rust 2018 imports a bunch of changes about those terms, and I want to find a good way to integrate them

**Comment by dumindu** [comment]
@ldwformat @juzhiyuan 👋 Thanks for considering to contribute Learning Rust project. 

As I mentioned earlier, I had some struggles in both my career and personal lives past years. Rust and this project had a less priority, because of that. But things are becoming stable on my side and I also tried to practice some Rust last days again after a very long time. 

Still I can not give exact time line about 2018 edition updates. However many projects still having(/prefer) the practices of 2015 edition like using mod.rs. So, I think, we have to keep both ways.

Can suggest two ways,
1. For the moment, try to add exact translations. And let's add 2018 edition updates in a separate ticket.
or
2. Mostly we need to add new content to cover https://doc.rust-lang.org/edition-guide/rust-2018/module-system/index.html. Feel free to add things in simplest and shortest ways and please let me know things you added. Also I'll help for this from middle of the next month.

Thanks

**Comment by ldwformat** [comment]
Ic. So I'll push a basic version contains the Chinese translation of the current contents in a few days, after that, we could add changes of rust 2018 in a convenient way. [Here](https://doc.rust-lang.org/edition-guide/index.html) maybe an useful material about that work. @juzhiyuan may you want to do a comparation between the current contents of site and this material? It will be a great help on the coming improvement work. Or u can talk with @dumindu about a suitable way to show the different parts between rust 2015/2018, I've seen your website and some other works you've done, those looks great.

**Comment by dumindu** [comment]
Sorry. Declining this due to long time inactivity

**Pull request closed without merging**
