### PR TITLE
I18n/cn

### PR DESCRIPTION
**Pull request by ldwformat**
Have trying to add some Chinese translations. The rest will be supplemented soon.

### CODE REVIEW

**Comment by dumindu** [comment]
Hey buddy,
Thanks a lot for start adding Chinese translations to the site. Really appreciate your work. 

Can you remove/revert following changes from the pull request?
- .gitignore , db.json
- files in public folder
- yarn.lock for the moment

Please commit only relevant .md files, index.jade and .yml files :)

**Comment by ldwformat** [comment]
Sorry for missing those points above. I did some revert for those files, please check wether they are apposite now. 
About the .gitignore file, I think there maybe some other entries should be added into it. Maybe, the public dir and the db.json should be candidates～

**Comment by dumindu** [comment]
Hi @ldwformat ,

Because of still we are having Chinese translations only for one file/a1.why_rust.md I don't think that it is a good idea to add `Chinese` on language switcher. 

So what is your plan? 
- Add all translated files + add `Chinese` on language switcher
- Add translated files separately without adding `Chinese` on language switcher
- Use a separate branch and merge to maser when all translated files were added

I prefer first or third options but let me know what do you think on this.

**Comment by ldwformat** [comment]
Hi, @dumindu ,

I'm agree with your idea. I think the third option will be a good choice for now and I'll add the translations asap :smiley:

**Comment by dumindu** [comment]
Hi,
Can you use `zh-cn` branch/ https://github.com/learning-rust/site/tree/zh-cn for the PR?

**Comment by ldwformat** [comment]
I can see it now, I'll propose an other RP~

**Pull request closed without merging**
